CREATE TABLE `books` (
	`id` int AUTO_INCREMENT NOT NULL,
	`slug` varchar(128) NOT NULL,
	`title` varchar(256) NOT NULL,
	`subtitle` varchar(256),
	`author` varchar(256) NOT NULL,
	`publisher` varchar(256),
	`year` int,
	`pages` int,
	`fileSizeBytes` bigint,
	`category` varchar(128),
	`description` text,
	`pdfKey` varchar(512) NOT NULL,
	`coverKey` varchar(512),
	`pdfUrl` varchar(1024) NOT NULL,
	`coverUrl` varchar(1024),
	`isbn` varchar(64),
	`featured` enum('0','1') NOT NULL DEFAULT '0',
	`downloadCount` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `books_id` PRIMARY KEY(`id`),
	CONSTRAINT `books_slug_unique` UNIQUE(`slug`)
);
